site_name: Arm Keil Studio for VS Code
repo_name: GitHub
repo_url: https://github.com/MDK-Packs/vscode-cmsis-solution-docs
edit_uri: edit/main/docs/
nav:
    - Home: index.md
    - Installation: installation.md
    - User Interface: userinterface.md
    - Create New Solution: create_app.md
    - Manage Solution: manage_settings.md
    - Software Components: manage_components.md
    - Debug: debug.md
    - Configuration: configuration.md
    - Import uVision Project: importuv.md
    - Run External Tools: runexternal.md
    - Tips and Tricks: tipsandtricks.md
theme:
  name: readthedocs
markdown_extensions:
  - admonition
extra_css:
  - css/extra.css
use_directory_urls: false
