site_name: CMSIS Solution for VS Code
repo_name: GitHub
repo_url: https://github.com/MDK-Packs/vscode-cmsis-solution-docs
edit_uri: edit/main/docs/
nav:
    - Home: index.md
    - Setup: installation.md
    - Quick start: quickstart.md
    - Create an embedded project: create_app.md
    - Manage software components: manage_components.md
    - Manage settings: manage_settings.md
    - Build a project: build.md
    - Flash the application: flash.md
    - Debug a project: debug.md
    - Configuration: configuration.md
    - Import uVision project: importuv.md
    - Run external tools: runexternal.md
    - Tips and tricks: tipsandtricks.md
theme:
  name: readthedocs
markdown_extensions:
  - admonition
extra_css:
  - css/extra.css
use_directory_urls: false
